# paths
ntl_wd: '/Users/ivan_zorin/Documents/DEV/code/ntl/'
data_path: '/Users/ivan_zorin/Documents/DEV/data/sgcc/data.csv'
log_path: '/Users/ivan_zorin/Documents/DEV/runs/'

# wandb logger
logger: 
  name: 'first-run' # name of run
  notes: ''
  project: 'ntl' 
  save_dir: '/Users/ivan_zorin/Documents/DEV/runs/'
  offline: True

# training params
n_epochs: 100
batch_size: 16
lr: 0.0001
device: 'cpu'

# model params
input_size: 1
hidden_size: [64]
n_lstms: 1

pca_dim: 2